flat_NeighborFinder.Rmd:
  path: dev/flat_NeighborFinder.Rmd
  state: active
  R:
  - R/apply_neighborfinder.R
  - R/apply_nf_simple.R
  - R/choose_params_values.R
  - R/compute_precision.R
  - R/compute_recall.R
  - R/cvglm_to_coeffs_by_object.R
  - R/final_step.R
  - R/find_all_module_neighbors.R
  - R/find_module_neighbors.R
  - R/get_count_table.R
  - R/graph_step.R
  - R/identify_module.R
  - R/intersections_network.R
  - R/intersections_table.R
  - R/mclr.R
  - R/module_to_node.R
  - R/new_synth_data.R
  - R/norm_data.R
  - R/prev_for_selected_nodes.R
  - R/simulate_by_prevalence.R
  - R/simulate_from_ecdf.R
  - R/test_filter.R
  - R/truth_by_prevalence.R
  - R/visualize_network.R
  - R/taxo-data.R
  - R/data-for-crc-patients.R
  - R/metadata-for-crc-patients.R
  - R/graphs-for-crc-patients.R
  - R/pipe-function.R
  tests:
  - tests/testthat/test-get_count_table.R
  - tests/testthat/test-module_to_node.R
  - tests/testthat/test-identify_module.R
  - tests/testthat/test-graph_step.R
  - tests/testthat/test-simulate_by_prevalence.R
  - tests/testthat/test-prev_for_selected_nodes.R
  - tests/testthat/test-truth_by_prevalence.R
  - tests/testthat/test-norm_data.R
  - tests/testthat/test-compute_precision.R
  - tests/testthat/test-compute_recall.R
  - tests/testthat/test-choose_params_values.R
  - tests/testthat/test-apply_nf_simple.R
  - tests/testthat/test-apply_neighborfinder.R
  - tests/testthat/test-intersections_table.R
  vignettes: []
  inflate:
    flat_file: dev/flat_NeighborFinder.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: ask
    clean: ask
    codecov: false
keep:
  path: keep
  state: active
  R: R/res_by_filtering.R
  tests: tests/testthat/test-res_by_filtering.R
  vignettes:
  - vignettes/NeighborFinder_technical_report.Rmd
  - vignettes/NeighborFinder_vignette.Rmd
