# WARNING - Generated by {fusen} from dev/NeighborFinder_flat.Rmd: do not edit by hand

test_that("msp_to_bact works", {
  df_taxo<-data.frame(msp_name=c("msp_1","msp_2","msp_3","msp_4"),
                    genus=c("A","B","C","D"),
                    species=c("A a","B a","C c","D b"))
  expect_equal(msp_to_bact("msp_1", taxo=df_taxo, col_msp_id = "msp_name"), "A a")
})
