# WARNING - Generated by {fusen} from dev/NeighborFinder_flat.Rmd: do not edit by hand

test_that("graph_step works", {
  data(data)
  data(graphs)
  expect_equal(graph_step(data$CRC_JPN_CHN_EUR, col_module_id="msp_id", annotation_level="species", seed=10010), graphs$CRC_JPN_CHN_EUR)
})
