# WARNING - Generated by {fusen} from dev/NeighborFinder_flat.Rmd: do not edit by hand

test_that("compute_recall works", {c(
  expect_equal(compute_recall(c("a"), c("a", "b", "c")), 100),
  expect_equal(compute_recall(c("a","b"), c("a", "c")), 50))
})
