# WARNING - Generated by {fusen} from dev/flat_NeighborFinder.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("get_count_table works", {
  tiny_data <- data.frame(
    msp_name = c("msp_1", "msp_2", "msp_3", "msp_4"),
    SAMPLE1 = c(0, 1.328425e-06, 0, 1.527688e-07),
    SAMPLE2 = c(1.251707e-07, 1.251707e-07, 3.985320e-07, 0),
    SAMPLE3 = c(0, 0, 4.926046e-09, 5.626392e-06),
    SAMPLE4 = c(0, 0, 2.98320e-05, 0)
  )
  expect_equal(get_count_table(abund.table = tiny_data, sample.id = colnames(tiny_data), prev.min = 0.3, verbatim = FALSE)$prevalences$msp, c("msp_2", "msp_3", "msp_4"))
})
