# WARNING - Generated by {fusen} from dev/NeighborFinder_flat.Rmd: do not edit by hand

test_that("graph_step works", {
  data(data)
  data(graphs)
  expect_equal(graph_step(data$CRC_JPN_CHN_EUR, col_msp_id="msp_id"), graphs$CRC_JPN_CHN_EUR)
})
