# WARNING - Generated by {fusen} from dev/NeighborFinder_flat.Rmd: do not edit by hand

test_that("apply_NeighborFinder works", {
  data(data)
  res_CRC_JPN<-apply_NeighborFinder(data$CRC_JPN, bact_of_interest="Escherichia coli", col_msp_id="msp_id", taxo_level="species", seed=20232024)
  expect_equal(res_CRC_JPN$msp2, c("msp_0103", "msp_0208", "msp_0030", "msp_2448"))
})
