# WARNING - Generated by {fusen} from dev/NeighborFinder_flat.Rmd: do not edit by hand

test_that("norm_data works", {
  tiny_data<-data.frame(species=c("One bacteria","One bacterium L","One bacterium G","Two bact"),
                        msp_name=c("msp_1","msp_2","msp_3","msp_4"),
                        SAMPLE1=c(0,1.328425e-06,0,1.527688e-07),
                        SAMPLE2=c(1.251707e-07,1.251707e-07,3.985320e-07,0),
                        SAMPLE3=c(0,0,4.926046e-09,5.626392e-06),
                        SAMPLE4=c(0,0,2.98320e-05,0))
  
  expected_normed0.2 <-data.frame(msp_1=c(0.00000,4.12841,0.00000,0.00000),
                                  msp_2=c(5.602486,4.128410,0.000000,0.000000),
                                  msp_3=c(0.000000,5.303984,1.000000,4.520268),
                                  msp_4=c(3.438051,0.000000,8.040536,0.000000))  
  rownames(expected_normed0.2)<-c("SAMPLE1","SAMPLE2","SAMPLE3","SAMPLE4")
  expect_equal(norm_data(tiny_data, col_module_id="msp_name",annotation_level="species", prev_list=c(0.20), type="fpkm")[[1]] %>% as.data.frame() %>% round(digits=5), expected_normed0.2 %>% round(digits=5))
})
