# WARNING - Generated by {fusen} from dev/NeighborFinder_flat.Rmd: do not edit by hand

test_that("norm_data works", {
  df_detected <- tibble::tibble(prev_level = c("0.20", "0.30", "0.30", "0.30"), msp1 = c("msp_2", "msp_2", "msp_3", "msp_3"), msp2 = c("msp_3", "msp_3", "msp_18", "msp_8"), coef = c(0.406, -0.025, 0.160, 0.005))
  expected_top20 <- structure(list(
    prev_level = "0.30", msp1 = "msp_3", msp2 = "msp_18",
    coef = 0.16
  ), row.names = c(NA, -1L), class = "data.frame")
  expect_equal(res_by_filtering(df_detected, filtering_list = c(20))[[1]] %>% as.data.frame() %>% dput(), expected_top20)
})
