# WARNING - Generated by {fusen} from dev/NeighborFinder_flat.Rmd: do not edit by hand

test_that("test_filter works", {
  #Generate dataframe with true neighbors
  df_true<-list(tibble::tibble(msp1=c("msp_1","msp_1","msp_2","msp_3"), msp2=c("msp_55","msp_20","msp_3","msp_18"), prev1=c(0.28,0.28,0.96,0.75), prev2=c(0.76,0.25,0.75,0.60)),
                tibble::tibble(msp1=c("msp_2","msp_3"), msp2=c("msp_3","msp_18"), prev1=c(0.96,0.75), prev2=c(0.75,0.60)))
  names(df_true)<-c("0.20","0.30")
  #Generate dataframe with detected neighbors
  df_detected<-tibble::tibble(prev_level=c("0.20","0.30","0.30","0.30"), msp1=c("msp_2","msp_2","msp_3","msp_3"), msp2=c("msp_3","msp_3","msp_18","msp_8"), coef=c(0.406,-0.025,0.160,0.005))
  #Use final_step() to gather both
  neighbors<-final_step(df_true, df_detected)
  neighbors_modif<-final_step(df_true, df_detected %>%  dplyr::filter(coef > 0))
  scores<-test_filter(neighbors, neighbors_modif, prevs=names(df_true))
  expect_equal(scores$recall_after, c(100*1/3,50))
})
