# WARNING - Generated by {fusen} from dev/flat_NeighborFinder.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("graph_step works", {
  tiny_data <- data.frame(
    species = c(
      "One bacteria",
      "One bacterium L",
      "One bacterium G",
      "Two bact",
      "Three bact A",
      "Three bact B"
    ),
    msp_name = c("msp_1", "msp_2", "msp_3", "msp_4", "msp_5", "msp_6"),
    SAMPLE1 = c(0, 1.328425e-06, 0, 1.527688e-07, 0, 0),
    SAMPLE2 = c(1.251707e-07, 0, 3.985320e-07, 0, 1.33607e-04, 0.8675e-03),
    SAMPLE3 = c(0, 0, 4.926046e-09, 5.626392e-06, 0, 0.662e-03),
    SAMPLE4 = c(0, 0, 2.98320e-05, 0, 1.275e-04, 0),
    SAMPLE5 = c(0.0976, 0.9862, 2.98320e-03, 0, 3.9754e-03, 0),
    SAMPLE6 = c(0.26417e-06, 0, 1.0077e-05, 3.983320e-08, 0, 0)
  )

  tiny_graph <- structure(
    list(
      msp_1 = c(0, 1, 0, 0, 0, 1),
      msp_2 = c(1, 0, 1, 1, 1, 0),
      msp_3 = c(0, 1, 0, 0, 1, 1),
      msp_4 = c(0, 1, 0, 0, 0, 1),
      msp_5 = c(0, 1, 1, 0, 0, 1),
      msp_6 = c(1, 0, 1, 1, 1, 0),
      species = c(
        "One bacteria",
        "One bacterium L",
        "One bacterium G",
        "Two bact",
        "Three bact A",
        "Three bact B"
      )
    ),
    row.names = c("msp_1", "msp_2", "msp_3", "msp_4", "msp_5", "msp_6"),
    class = "data.frame"
  )

  expect_equal(
    graph_step(
      tiny_data,
      col_module_id = "msp_name",
      annotation_level = "species",
      seed = 20242025
    ) %>%
      suppressWarnings(),
    tiny_graph
  )
})
