# WARNING - Generated by {fusen} from dev/flat_NeighborFinder.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("SimCluster works", {
  expect_true(inherits(SimCluster, "function"))
})
