# WARNING - Generated by {fusen} from dev/NeighborFinder_flat.Rmd: do not edit by hand

test_that("truth_by_prevalence works", {
  tiny_truth <-tibble::tibble(msp1=c("msp_2","msp_2","msp_2","msp_3","msp_3"),
                              msp2=c("msp_1","msp_3","msp_4","msp_2","msp_4"),
                              prev1=c(0.5,0.5,0.5,0.75,0.75),
                              prev2=c(0.25,0.75,0.5,0.5,0.5))
  
  expected_true_edges0.3 <- tibble::tibble(msp1=c("msp_2", "msp_2", "msp_3", "msp_3"),
                                           msp2=c("msp_3","msp_4","msp_2","msp_4"),
                                           prev1=c(0.5,0.5,0.75,0.75),
                                           prev2=c(0.75,0.5,0.5,0.5))
  expect_equal(truth_by_prevalence(tiny_truth, c(0.30))[[1]], expected_true_edges0.3)
})
