# WARNING - Generated by {fusen} from dev/flat_NeighborFinder.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("compute_precision works", {
  c(
    expect_equal(compute_precision(c("a"), c("a", "b", "c")), 1 / 3),
    expect_equal(compute_precision(c("a", "b"), c("a", "c")), 0.50)
  )
})
