# WARNING - Generated by {fusen} from dev/flat_NeighborFinder.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("compute_recall works", {
  c(
    expect_equal(compute_recall(c("a"), c("a", "b", "c")), 1),
    expect_equal(compute_recall(c("a", "b"), c("a", "c")), 0.50)
  )
})
