# WARNING - Generated by {fusen} from dev/NeighborFinder_flat.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("apply_NeighborFinder works", {
  data(data)
  res_CRC_JPN<-apply_NeighborFinder(data$CRC_JPN, object_of_interest="Escherichia coli", col_module_id="msp_id", annotation_level="species")
  expect_equal(res_CRC_JPN$node2, c("msp_0103", "msp_0208", "msp_2448"))
})
