# WARNING - Generated by {fusen} from dev/flat_NeighborFinder.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("apply_NF_simple works", {
  data(data)
  res_CRC_JPN <- apply_NF_simple(
    data$CRC_JPN[, 1:100],
    object_of_interest = "Escherichia coli",
    col_module_id = "msp_id",
    annotation_level = "species",
    seed = 20242025
  )
  expect_equal(
    res_CRC_JPN$node2[1:4],
    c("msp_0154", "msp_0565", "msp_0570", "msp_1684")
  )
})
