# WARNING - Generated by {fusen} from dev/NeighborFinder_flat.Rmd: do not edit by hand

test_that("identify_msp works", {
  df_taxo<-data.frame(msp_name=c("msp_1","msp_2","msp_3","msp_4"),
                    genus=c("One","One","One","Two"),
                    species=c("One bacteria","One bacterium L","One bacterium G","Two bact"))
  expect_equal(identify_msp("One", taxo=df_taxo, col_msp_id = "msp_name"), c("msp_1", "msp_2", "msp_3"))
})
