# WARNING - Generated by {fusen} from dev/NeighborFinder_flat.Rmd: do not edit by hand

test_that("choose_prev_level works", {
  data(data)
  data(graphs)
  simulations <- simulate_by_prevalence(data$CRC_JPN, prev_list=c(0.20,0.30), graph_file=graphs$CRC_JPN, col_msp_id="msp_id", seed=20232024)
  scores<-choose_prev_level(data$CRC_JPN, "Escherichia coli", simulations, graph_file = graphs$CRC_JPN, col_msp_id="msp_id", seed = 20232024)
  expect_equal(scores$precision_before %>% round(digits=2), c(25, 25))
})
