# WARNING - Generated by {fusen} from dev/NeighborFinder_flat.Rmd: do not edit by hand

test_that("module_to_node works", {
  df_taxo<-data.frame(msp_name=c("msp_1","msp_2","msp_3","msp_4"),
                    genus=c("A","B","C","D"),
                    species=c("A a","B a","C c","D b"))
  expect_equal(module_to_node("msp_1", annotation_table=df_taxo, col_module_id = "msp_name", annotation_level="species"), "A a")
})
