# WARNING - Generated by {fusen} from dev/NeighborFinder_flat.Rmd: do not edit by hand

#' Render a table to give an indication of the values to choose for the prevalence level and the top filtering percentage
#' 
#' @param data_with_annotation Dataframe. The abundance table merged with the module names. Required format: modules are the rows and samples are the columns. The first column must be the modules name (e.g. species), the second is the module ID (e.g. msp), and each subsequent column is a sample
#' @param object_of_interest String. The name of the bacteria or species of interest or a key word in the functional module definition
#' @param list_sims List of dataframes. The result of simulate_by_prevalence()
#' @param prev_list List of numeric. The prevalences to be studied. Required format is decimal: 0.20 for 20% of prevalence
#' @param filtering_list List of numeric. The filtering top percentages to be studied. Required format is: 10 for the top 10% 
#' @param graph_file Dataframe. The object generated by graph_step() function
#' @param col_module_id String. The name of the column with the module names in annotation_table
#' @param annotation_level String. The name of the column with the level to be studied. Examples: species, genus, level_1
#' @param seed Numeric. The seed number, ensuring reproducibility
#'  
#' @return Dataframe. Returns F1 rates before and after using NeighborFinder()
#' @export
#' @examples
#' data(data)
#' data(graphs)
#' simulations <- simulate_by_prevalence(data$CRC_JPN, prev_list=c(0.20,0.30), graph_file=graphs$CRC_JPN, col_module_id="msp_id", annotation_level="species", seed=20232024)
#' choose_params_values(data$CRC_JPN, "Klebsiella", simulations, filtering_list=c(10,20), graph_file = graphs$CRC_JPN, col_module_id="msp_id", annotation_level="species", seed = 20232024)

choose_params_values <- function(data_with_annotation, object_of_interest, list_sims, prev_list=NULL, filtering_list=c(0.20), graph_file=NULL, col_module_id, annotation_level, seed=NULL){
 
 #Loading graph
 if (is.null(graph_file)) {stop("Please generate the graph beforehand with graph_step() function")}
 else {G <- graph_file}
 
 # Extract edge_prevalence table for species of interest
 true_edges <- prev_for_selected_nodes(data_with_annotation, graph_file, col_module_id, annotation_level, object_of_interest)
 if(!nrow(true_edges)){return(tibble::tibble())}
 
 prevs<-as.numeric(names(list_sims))
 list_truth <- truth_by_prevalence(true_edges, prevs)
 
 #Applying  glmnet
 df_glm<-cvglm_to_coeffs_by_object(list_sims, test_module=identify_module(object_of_interest=object_of_interest, annotation_table=data_with_annotation, col_module_id=col_module_id, annotation_level=annotation_level), seed=seed)
 if(!nrow(df_glm)){return(tibble::tibble())}
 
 #Filtering results & rendering table
 cat("Calculating scores...\n")
 before<-final_step(list_truth, df_glm)
 after<-final_step(list_truth, res_by_filtering(df_glm,filtering_list))
 
 if (any(!prev_list %in% prevs)) {stop("The prevalence levels selected are not found in the simulations file. Please try another set of prevalences")}
 else {
  harm_mean<-function(P,R){
   hm<-2*(P*R)/(P+R)
   hm
  }
  res<-test_filter(before, after, prev_list) %>% 
   dplyr::mutate(F1_before=harm_mean(precision_before, recall_before)) %>% 
   dplyr::mutate(F1_after=harm_mean(precision_after, recall_after)) %>% 
   dplyr::select(-precision_before,-recall_before,-precision_after,-recall_after)
  res$F1_before[is.na(res$F1_before)] <- 0
  res$F1_after[is.na(res$F1_after)] <- 0
  
  if (!nrow(res)){return(tibble::tibble())}
  else{res %>%  dplyr::mutate(prev_level=as.numeric(prev_level))}
 }
}
