# WARNING - Generated by {fusen} from dev/NeighborFinder_flat.Rmd: do not edit by hand

#' Render a table gathering precision and recall rates before and after filtering on coefficient values
#' 
#' @param data_with_taxo Dataframe. The abundance table merged with the species names. Required format: species are the rows and samples are the columns. The first column must be the species name, the second is the msps name, and each subsequent column is a sample
#' @param bact_of_interest String. The name of the bacteria or species of interest
#' @param list_sims List of dataframes. The result of simulate_by_prevalence()
#' @param prev_list List of numeric. The prevalences to be studied. Required format is decimal: 0.20 for 20% of prevalence
#' @param graph_file Dataframe. The object generated by graph_step() function
#' @param col_msp_id String. The name of the column with the msp names in taxo
#' @param seed Numeric. The seed number, ensuring reproducibility
#'  
#' @return Dataframe. Returns precision and recall rates before and after using NeighborFinder()
#' @export
#' @examples
#' data(data)
#' data(graphs)
#' simulations <- simulate_by_prevalence(data$CRC_JPN, prev_list=c(0.20,0.30), graph_file=graphs$CRC_JPN, col_msp_id="msp_id", seed=20232024)
#' choose_prev_level(data$CRC_JPN, "Escherichia coli", simulations, graph_file = graphs$CRC_JPN, col_msp_id="msp_id", seed = 20232024)

choose_prev_level <- function(data_with_taxo, bact_of_interest, list_sims, prev_list=NULL, graph_file=NULL, col_msp_id, seed=NULL){
  
  #Loading graph
  if (is.null(graph_file)) {stop("Please generate the graph beforehand with graph_step() function")}
  else {G <- graph_file}
  
  # Extract edge_prevalence table for species of interest
  true_edges <- prev_for_selected_nodes(data_with_taxo, graph_file, col_msp_id, bact_of_interest)
  if(!nrow(true_edges)){return(tibble::tibble())}
  
  prevs<-as.numeric(names(list_sims))
  list_truth <- truth_by_prevalence(true_edges, prevs)
  
  #Applying  glmnet
  df_glm<-cvglm_to_coeffs_by_bact(list_sims, test_msp=identify_msp(bact_of_interest=bact_of_interest, taxo=data_with_taxo, col_msp_id=col_msp_id), seed=seed)
  if(!nrow(df_glm)){return(tibble::tibble())}
  
  #Filtering results & rendering table
  cat("Calculating scores...\n")
  before<-final_step(list_truth, df_glm)
  after_top20<-final_step(list_truth, df_glm %>% dplyr::group_by(prev_level) %>% dplyr::mutate(coef=abs(coef)) %>%  dplyr::filter(coef > quantile(coef,0.8)) %>% dplyr::ungroup())
  
  if (any(!prev_list %in% prevs)) {stop("The prevalence levels selected are not found in the simulations file. Please try another set of prevalences")}
  else {res<-test_filter(before, after_top20, prev_list) 
  if (!nrow(res)){return(tibble::tibble())}
  else{res %>%  dplyr::mutate(prev_level=as.numeric(prev_level))}
  }
}
