# WARNING - Generated by {fusen} from dev/NeighborFinder_flat.Rmd: do not edit by hand

#' Compute precision rate
#' 
#' @param true List. The one of true neighbors
#' @param detected List. The one of detected neighbors
#' 
#' @return Numeric. Returns the precision rate in %
#' @export
#' @examples
#' compute_precision(c("a"), c("a", "b", "c"))
#' compute_precision(c("a","b"), c("a", "c"))

compute_precision <- function(true, detected) {
  if (length(detected) == 0) return(0)
  ## TP / (TP + FP)
  100 * length(intersect(true, detected)) / length(detected)
}
