# WARNING - Generated by {fusen} from dev/NeighborFinder_flat.Rmd: do not edit by hand # nolint: line_length_linter.

#' Compute recall rate
#' 
#' @param true List. The one of true neighbors
#' @param detected List. The one of detected neighbors
#' 
#' @return Numeric. Returns the recall rate
#' @export
#' @examples
#' compute_recall(c("a"), c("a", "b", "c"))
#' compute_recall(c("a","b"), c("a", "c"))

compute_recall <- function(true, detected) {
  if (length(true) == 0) return(0)
  ## TP / (TP + FN)
  length(intersect(true, detected)) / length(true)
}
