# WARNING - Generated by {fusen} from dev/NeighborFinder_flat.Rmd: do not edit by hand

#' Apply cv.glmnet() for a list of msps and for each prevalence level
#' 
#' @param list_dfs List of dataframe. A normalized dataframe
#' @param test_msp List of string. The msp names
#' @param seed Numeric. The seed number, ensuring reproducibility
#' @param covar String or formula. Formula or the name of the column of the covariate in the metadata table. Note that "study_accession" is equivalent to ~study_accession
#' @param meta_df Dataframe. The dataframe giving metadata information
#' @param sample_col String. The name of the column in metadata indicating the sample names, it should be consistent with the colnames of 'df'
#' 
#' @return Dataframe. Returns the msp, its detected neighbor and the corresponding coefficient 
#' @export
#' @examples
#' data(data)
#' data(metadata)
#' #Simple example
#' normed_JPN <-norm_data(data$CRC_JPN, col_msp_id="msp_id", prev_list=c(0.20, 0.25, 0.30), type="fpkm")
#' neighbors_JPN<-cvglm_to_coeffs_by_bact(list_dfs=normed_JPN, test_msp=c("msp_0030","msp_0345"), seed=20232024)
#' #Example with covariate
#' normed_CHN <-norm_data(data$CRC_CHN, col_msp_id="msp_id", prev_list=c(0.20, 0.25, 0.30), type="fpkm")
#' neighbors_CHN<-cvglm_to_coeffs_by_bact(list_dfs=normed_CHN, test_msp=c("msp_0030","msp_0345"), seed=20232024, covar= ~ study_accession, meta_df=metadata$CRC_CHN, sample_col="secondary_sample_accession")

cvglm_to_coeffs_by_bact<-function(list_dfs, test_msp = identify_msp(), seed=NULL, ...){
  cat("Applying NeighborFinder to detect neighbors...\n")
  purrr::map(list_dfs, function(df) find_all_msp_neighbors(df, test_msp, seed, ...)) %>% 
    dplyr::bind_rows(.id = "prev_level")
}
