# WARNING - Generated by {fusen} from dev/NeighborFinder_flat.Rmd: do not edit by hand

#' Apply cv.glmnet() for a list of msps
#' 
#' @param df Dataframe. A normalized dataframe
#' @param test_msp List of string. The msp names
#' @param seed Numeric. The seed number, ensuring reproducibility
#' @param covar String or formula. Formula or the name of the column of the covariate in the metadata table. Note that "study_accession" is equivalent to ~study_accession
#' @param meta_df Dataframe. The dataframe giving metadata information
#' @param sample_col String. The name of the column in metadata indicating the sample names, it should be consistent with the colnames of 'df'
#' 
#' @return Dataframe. Returns the msp, its detected neighbor and the corresponding coefficient 
#' @export
#' @examples
#' data(data)
#' data(metadata)
#' #Simple example
#' x <- norm_data(data$CRC_JPN, 0.30, type="fpkm")[[1]]
#' neighbors_JPN<-find_all_msp_neighbors(df=x, test_msp=c("msp_0030","msp_0345"), seed=20232024)
#' # Example with covariate
#' x <- norm_data(data$CRC_CHN, 0.30, type="fpkm")[[1]]
#' neighbors_CHN<-find_all_msp_neighbors(df=x, test_msp=c("msp_0030","msp_0345"), seed=20232024, covar= ~ study_accession, meta_df=metadata$CRC_CHN, sample_col="secondary_sample_accession")

find_all_msp_neighbors <- function(df, test_msp, seed=NULL, ...) {
  purrr::map(test_msp, function(x) find_msp_neighbors(df, x, seed, ...)) %>% dplyr::bind_rows()
}
