# WARNING - Generated by {fusen} from dev/NeighborFinder_flat.Rmd: do not edit by hand

#' Conversion to count table function with prevalence filter (Extracted from OneNet package)
#' 
#' @param abund.path String. Path to the abundance table
#' @param abund.table Dataframe. Abundance table, it should have the bacterial species names as first column
#' @param sample.id String vector. IDs of samples to keep in the final table
#' @param prev.min Numeric. The value is between 0 and 1 and corresponds to the minimal prevalence threshold of bacterial species to keep in the final table
#' @param msp String vector. It indicates bacterial species names, if they are not specified in the abundance table first column
#' @param verbatim Boolean. Controls verbosity
#'
#' @return A list containing
#' \itemize{
#'  \item{data: }{the final count table (tibble)}
#'  \item{prevalences: }{a tibble gathering the prevalence of each bacterial species}
#'}
#' @export
#' @examples
#' tiny_data<-data.frame(msp_name=c("msp_1","msp_2","msp_3","msp_4"),
#'                       SAMPLE1=c(0,1.328425e-06,0,1.527688e-07),
#'                       SAMPLE2=c(1.251707e-07,1.251707e-07,3.985320e-07,0),
#'                       SAMPLE3=c(0,0,4.926046e-09,5.626392e-06),
#'                       SAMPLE4=c(0,0,2.98320e-05,0))
#' # Applying a prevalence filter of 30% on the new count_table
#' get_count_table(abund.table=tiny_data, sample.id=colnames(tiny_data), prev.min=0.3)

get_count_table<-function(abund.path=NULL, abund.table=NULL, sample.id=NULL, prev.min, verbatim=TRUE, msp=NULL){
  if(!is.null(abund.path)){
    metaformat<-tail(strsplit(abund.path,"[.]")[[1]],1)
    if(metaformat=="rds"){ data_table <- as.matrix(readRDS(abund.path)) }
    else{ data_table <- as.matrix(read.delim(abund.path)) }
  }
 else{ data_table<-abund.table }
 
  if(is.null(msp)){
    species<-data_table[,1]
    data_table<-data_table[,-1]
  }
 else{ species<-msp }

  data_table<-apply(data_table,2,function(x){ as.numeric(x) })
  pct_zero_before=sum(data_table==0)/length(data_table)
  data_table<-tibble::as_tibble(data_table)

  if(!is.null(sample.id)){ data_table<-data_table[,colnames(data_table)%in%sample.id] }

  #Prevalence filtering
  counts<-data_table %>% dplyr::mutate(prev=rowMeans(.>0),msp=species) %>% dplyr::filter(prev>prev.min)
  prevs<-counts %>% dplyr::select(prev, msp)
  counts=counts %>% dplyr::select(-msp, -prev) %>% t(.)
  colnames(counts)<-prevs$msp
  #Set minimal positive value to 1
  cst=1/min(counts[counts!=0])
  counts=round(counts*cst)
  
  #Verbatim
  pct_zero_after=sum(counts==0)/length(counts)
  if(verbatim){cat(paste0("Preprocessing step output for species prevalence>",
                          prev.min*100,"% : \n   -from ", length(species),
                          " to ", ncol(counts)," species","\n   -from ",
                          round(pct_zero_before*100,1),"% to ",
                          round(pct_zero_after*100,1),"% zero values."))}

  return(list(data=counts, prevalences=prevs))
}

