# WARNING - Generated by {fusen} from dev/NeighborFinder_flat.Rmd: do not edit by hand

#' Generate a graph
#' 
#' @param data_with_taxo Dataframe. The abundance table merged with the species names. Required format: species are the rows and samples are the columns. The first column must be the species name, the second is the msps name, and each subsequent column is a sample
#' @param col_msp_id String. The name of the column with the msp names in taxo
#' @param type String. Default value is "fpkm". If your dataset is not of type "fpkm", indicate one of the following equivalent words in 'type' argument: "comptage","couverture","coverage"
#'
#' @return Dataframe. The dataframe is composed of 0 and 1 corresponding to the existence of edges on the graph.
#' @export
#' @examples
#' tiny_data<-data.frame(species=c("One bacteria","One bacterium L","One bacterium G","Two bact"),
#'                       msp_name=c("msp_1","msp_2","msp_3","msp_4"),
#'                       SAMPLE1=c(0,1.328425e-06,0,1.527688e-07),
#'                       SAMPLE2=c(1.251707e-07,1.251707e-07,3.985320e-07,0),
#'                       SAMPLE3=c(0,0,4.926046e-09,5.626392e-06),
#'                       SAMPLE4=c(0,0,2.98320e-05,0))
#'
#' tiny_graph<-graph_step(tiny_data, col_msp_id="msp_name", type="fpkm") %>% suppressWarnings()

graph_step<-function(data_with_taxo, col_msp_id, type="fpkm"){
  if (type %in% c("couverture","coverage","comptage")){
    prev_df <- data_with_taxo %>%
      dplyr::mutate(prev = data_with_taxo %>% dplyr::select(-species, -all_of(col_msp_id)) %>% data.matrix() %>% `>`(0) %>% rowMeans())
    df <- prev_df %>% dplyr::filter(prev>0.15) %>% 
      dplyr::select(-species, -all_of(col_msp_id), -prev) %>% t() 
    colnames(df) <- prev_df %>% dplyr::filter(prev>0.15) %>% dplyr::pull(paste(col_msp_id))
    G <- OneNet::new_synth_data(df, n=50, plot=FALSE, verbose=FALSE)$G
    dimnames(G) <- list(colnames(df), colnames(df))
  }
  if (type %in% c("fpkm")){
    counts <- OneNet::get_count_table(abund.table = data_with_taxo %>% dplyr::select(-species), sample_id=colnames(data_with_taxo), prev.min=0.15, verbatim=FALSE)$data
    G <- OneNet::new_synth_data(counts, n=50, plot=FALSE, verbose=FALSE)$G
    dimnames(G) <- list(colnames(counts), colnames(counts))
  }
  G <- G %>% as.data.frame() %>% 
    dplyr::mutate(species=msp_to_bact(rownames(G), taxo=data_with_taxo, col_msp_id=col_msp_id))
  G
}
