# WARNING - Generated by {fusen} from dev/flat_NeighborFinder.Rmd: do not edit by hand # nolint: line_length_linter.

#' Generate a graph with a "cluster-like" structure, only needed for simulation purposes
#'
#' @param data_with_annotation Dataframe. The abundance table merged with the module names. Required format: modules are the rows and samples are the columns. The first column must be the modules name (e.g. species), the second is the module ID (e.g. msp), and each subsequent column is a sample
#' @param col_module_id String. The name of the column with the module names in the annotation table
#' @param annotation_level String. The name of the column with the level to be studied. Examples: species, genus, level_1
#' @param seed Numeric. Seed number for data generation (new_synth_data)
#' @param data_type String. Enables the treatment of 16S data with "16S", default value is "shotgun"
#'
#' @return Dataframe. The dataframe is composed of 0 and 1 corresponding to the existence of edges on the graph.
#' @export
#' @examples
#' tiny_data <- data.frame(
#'   species = c("One bacteria", "One bacterium L", "One bacterium G", "Two bact"),
#'   msp_name = c("msp_1", "msp_2", "msp_3", "msp_4"),
#'   SAMPLE1 = c(0, 1.328425e-06, 0, 1.527688e-07),
#'   SAMPLE2 = c(1.251707e-07, 1.251707e-07, 3.985320e-07, 0),
#'   SAMPLE3 = c(0, 0, 4.926046e-09, 5.626392e-06),
#'   SAMPLE4 = c(0, 0, 2.98320e-05, 0)
#' )
#'
#' tiny_graph <- graph_step(tiny_data, col_module_id = "msp_name", annotation_level = "species", seed = 20242025) %>% suppressWarnings()
graph_step <- function(data_with_annotation, col_module_id, annotation_level, seed = 10010, data_type = "shotgun") {
  if (data_type == "shotgun") {
    counts <- get_count_table(abund.table = data_with_annotation %>% dplyr::select(-!!rlang::sym(annotation_level)), sample.id = colnames(data_with_annotation), prev.min = 0.15, verbatim = FALSE)$data
  } else if (data_type == "16S") {
    ## Compute prevalence of all modules at the studied level
    prev_df <- tibble::tibble(
      id_module = data_with_annotation %>% dplyr::pull(paste(col_module_id)),
      prevalence = data_with_annotation %>% dplyr::select(-!!rlang::sym(annotation_level), -!!rlang::sym(col_module_id)) %>%
        data.matrix() %>% `>`(0) %>% rowMeans()
    )
    prev_df_filtered <- prev_df %>% dplyr::filter(prevalence > 0.15)
    data_with_annotation_filtered <- data_with_annotation %>% dplyr::filter(!!rlang::sym(col_module_id) %in% prev_df_filtered$id_module)
    counts <- data_with_annotation_filtered %>%
      dplyr::select(-!!rlang::sym(annotation_level), -!!rlang::sym(col_module_id)) %>%
      t()
    colnames(counts) <- data_with_annotation_filtered %>% dplyr::pull(paste(col_module_id))
  }
  G <- new_synth_data(counts, n = 50, verbatim = FALSE, seed = seed)$G
  dimnames(G) <- list(colnames(counts), colnames(counts))
  G <- G %>%
    as.data.frame() %>%
    dplyr::mutate(!!rlang::sym(annotation_level) := module_to_node(rownames(G), annotation_table = data_with_annotation, col_module_id = col_module_id, annotation_level = annotation_level))
  G
}
