# WARNING - Generated by {fusen} from dev/NeighborFinder_flat.Rmd: do not edit by hand

#' List the modules corresponding to a given object of interest
#' 
#' @param object_of_interest String. The name of the bacteria or species of interest or a key word in the functional module definition
#' @param annotation_table Dataframe. The dataframe gathering the taxonomic or functional module correspondence information 
#' @param col_module_id String. The name of the column with the module names in the annotation table
#' @param annotation_level String. The name of the column with the level to be studied. Examples: species, genus, level_1. Default value is set to the species level
#'
#' @return List of string. The module names of the corresponding object of interest
#' @export
#' @examples
#' df_taxo<-data.frame(msp_name=c("msp_1","msp_2","msp_3","msp_4"),
#'                     genus=c("One","One","One","Two"),
#'                     species=c("One bacteria","One bacterium L","One bacterium G","Two bact"))
#' identify_module(object_of_interest="bacterium", annotation_table=df_taxo, col_module_id = "msp_name", annotation_level="species")
#' identify_module(object_of_interest="One", annotation_table=df_taxo, col_module_id = "msp_name", annotation_level="species")

identify_module <-function(object_of_interest, annotation_table, col_module_id, annotation_level = "species"){
  res<-annotation_table %>% 
    dplyr::filter(stringr::str_detect(!!rlang::sym(annotation_level), object_of_interest)) %>% 
    dplyr::pull(paste(col_module_id)) %>% 
    as.character()
  if (length(res)==0) {stop("ERROR: Please check spelling of object_of_interest :)")}
  else {res}
}
