# WARNING - Generated by {fusen} from dev/flat_NeighborFinder.Rmd: do not edit by hand # nolint: line_length_linter.

#' Display the intersection table summarizing the results from 2 or more datasets
#'
#' @param res_list List of dataframes. The results from apply_NeighborFinder() on several datasets
#' @param threshold Numeric. Integer corresponding to the minimum number of datasets in which you want neighbors to have been found
#' @param annotation_table Dataframe. The dataframe gathering the taxonomic or functional module correspondence information
#' @param col_module_id String. The name of the column with the module names in annotation_table
#' @param annotation_level String. The name of the column with the level to be studied. Examples: species, genus, level_1
#' @param object_of_interest String. The name of the bacteria or species of interest or a key word in the functional module definition
#'
#' @return Dataframe. Table gathering the intersection of NeighborFinder results from several datasets. The column 'datasets' indicates the datasets in which the same neighbor has been found, the column 'intersections' indicates the number of datasets in which the same neighbor has been found
#' @export
#' @examples
#' data(taxo)
#' data(data)
#' data(metadata)
#' res_CRC_JPN <- apply_NeighborFinder(data$CRC_JPN, object_of_interest = "Escherichia coli", col_module_id = "msp_id", annotation_level = "species")
#' res_CRC_CHN <- apply_NeighborFinder(data$CRC_CHN, object_of_interest = "Escherichia coli", col_module_id = "msp_id", annotation_level = "species", covar = ~study_accession, meta_df = metadata$CRC_CHN, sample_col = "secondary_sample_accession")
#' res_CRC_EUR <- apply_NeighborFinder(data$CRC_EUR, object_of_interest = "Escherichia coli", col_module_id = "msp_id", annotation_level = "species", covar = ~study_accession, meta_df = metadata$CRC_EUR, sample_col = "secondary_sample_accession")
#'
#' intersections_table(res_list = list(res_CRC_JPN, res_CRC_CHN, res_CRC_EUR), threshold = 2, taxo, col_module_id = "msp_id", annotation_level = "species", "Escherichia coli")
intersections_table <- function(res_list, threshold, annotation_table, col_module_id, annotation_level, object_of_interest) {
  # Gathering all results from datasets
  for (l in 1:length(res_list)) {
    res_list[[l]] <- res_list[[l]] %>% dplyr::mutate(dataset = paste("n_", l))
  }
  # Counting in how many cohorts each neighbor was found
  inter <- dplyr::bind_rows(res_list) %>%
    tibble::tibble() %>%
    dplyr::mutate(pair = paste(node1, node2, sep = "_")) %>%
    dplyr::group_by(pair) %>%
    dplyr::summarize(datasets = list(dataset), intersections = list(dataset) %>% unlist() %>% length(), mean_coef = mean(coef)) %>%
    dplyr::ungroup() %>%
    tidyr::separate(pair, into = c("node1", "node2"), sep = "_msp") %>%
    dplyr::mutate(node2 = paste0("msp", node2))

  # Keeping only neighbors found in more than n cohort(s)
  res_intersections <- inter %>% dplyr::filter(intersections >= threshold)
  if (nrow(res_intersections) == 0) {
    return(message("No intersection was found between the results provided, try to lower the threshold.\n"))
  }
  # Give taxonomic correspondence
  res_intersections %>%
    dplyr::mutate(
      module1 = module_to_node(module = node1, annotation_table = annotation_table, col_module_id = col_module_id, annotation_level = annotation_level),
      module2 = module_to_node(module = node2, annotation_table = annotation_table, col_module_id = col_module_id, annotation_level = annotation_level)
    ) %>%
    dplyr::select(node1, module1, node2, module2, datasets, intersections, mean_coef) %>%
    as.data.frame()
}
