# WARNING - Generated by {fusen} from dev/NeighborFinder_flat.Rmd: do not edit by hand

#' Display the intersection network from 2 or more datasets
#' 
#' @param res_list List of dataframes. The results from apply_NeighborFinder() on several datasets
#' @param threshold Numeric. Integer corresponding to the minimum number of datasets in which you want neighbors to have been found
#' @param taxo Dataframe. The dataframe gathering the taxonomic correspondence information
#' @param col_msp_id String. The name of the column with the msp names in taxo
#' @param taxo_level String. The name of the column of the taxonomic level to be studied in taxo
#' @param bact_of_interest String. The name of the bacteria or species of interest
#' @param taxo_option Boolean. Default value is False. If True: labels on nodes become species names instead of msps names
#' @param node_size Numeric. The parameter to adjust size of nodes
#' @param label_size Numeric. The parameter to adjust size of labels
#' @param species_color String. The name of the color to differentiate the nodes corresponding to 'bact_of_interest' from the other msps
#' @param seed Numeric. The seed number, ensuring reproducibility
#' 
#' @return Network. Visualization of NeighborFinder results from several datasets
#' @export
#' @examples
#' data(taxo)
#' data(data)
#' data(metadata)
#' res_CRC_JPN<-apply_NeighborFinder(data$CRC_JPN, bact_of_interest="Escherichia coli", col_msp_id="msp_id", taxo_level="species", seed=20232024)
#' res_CRC_CHN<-apply_NeighborFinder(data$CRC_CHN, bact_of_interest="Escherichia coli", col_msp_id="msp_id", taxo_level="species", seed=20232024, covar= ~ study_accession, meta_df=metadata$CRC_CHN, sample_col="secondary_sample_accession")
#' res_CRC_EUR<-apply_NeighborFinder(data$CRC_EUR, bact_of_interest="Escherichia coli", col_msp_id="msp_id", taxo_level="species", seed=20232024, covar= ~ study_accession, meta_df=metadata$CRC_EUR, sample_col="secondary_sample_accession")
#'
#' intersections_network(res_list=list(res_CRC_JPN, res_CRC_CHN, res_CRC_EUR), taxo, threshold=2, "Escherichia coli", col_msp_id="msp_id", taxo_level="species", label_size=5, taxo_option=TRUE, seed=3)

intersections_network<-function(res_list, threshold, taxo, col_msp_id, taxo_level, bact_of_interest, taxo_option=FALSE, node_size=12, label_size=4, species_color="cadetblue2", seed=NULL){
  #Gathering all results from datasets
  for (l in 1:length(res_list)){res_list[[l]] <- res_list[[l]] %>%  dplyr::mutate(dataset=l)}
  inter <-  dplyr::bind_rows(res_list) %>% tibble::tibble() %>%  dplyr::select(-coef) %>% 
     dplyr::summarize(datasets=list(dataset), .by=c(msp1,msp2))
  #Counting in how many cohorts each neighbor was found
  res_intersections <- inter %>%  dplyr::rowwise() %>% 
     dplyr::mutate(intersections = datasets %>% unlist() %>% length()) 
  #Keeping only neighbors found in more than n cohort(s)
  res_intersections <- res_intersections %>%  dplyr::filter(intersections >= threshold) %>%  dplyr::select(msp1,msp2,intersections)
  if (nrow(res_intersections)==0){return(message("No intersection was found between the results provided, try to lower the threshold.\n"))}
  if (!taxo_option){
    #Build network
    net <- network::network(res_intersections, matrix.type = "edgelist", ignore.eval = FALSE, names.eval = "weights")
    edges<-res_intersections$intersections
    #Identify species of interest in a different color
    palette <- dplyr::if_else(network::network.vertex.names(net) %in% identify_msp(bact_of_interest=bact_of_interest, taxo=taxo, col_msp_id=col_msp_id, taxo_level=taxo_level), species_color, "grey85")
    #Plot network
    if (!is.null(seed)){set.seed(seed)}
    GGally::ggnet2(net, edge.size = "weights", 
           color=palette, edge.color="lightsteelblue4", size=node_size,
           edge.label=edges, edge.label.color = "white", edge.label.fill = "lightsteelblue4",
           label=TRUE, legend.position = "none", max_size=label_size)
  }
  else{
    #Give taxonomic correspondence
    res_intersections <- res_intersections %>%  dplyr::mutate(msp1=msp_to_bact(msp=msp1, taxo=taxo, col_msp_id=col_msp_id), 
                                                      msp2=msp_to_bact(msp=msp2, taxo=taxo, col_msp_id=col_msp_id)) 
    #Build network
    net <- network::network(res_intersections, matrix.type = "edgelist", ignore.eval = FALSE, names.eval = "weights")
    edges<-res_intersections$intersections
    #Identify species of interest in a different color
    palette <- dplyr::if_else(network::network.vertex.names(net) %in% msp_to_bact(msp=identify_msp(bact_of_interest=bact_of_interest, taxo=taxo, col_msp_id=col_msp_id, taxo_level=taxo_level), 
                                                                  taxo=taxo, col_msp_id=col_msp_id), species_color, "grey85")
    #Plot network
    if (!is.null(seed)){set.seed(seed)}
    GGally::ggnet2(net, edge.size = "weights", 
           color=palette, edge.color="lightsteelblue4", size=node_size,
           edge.label=edges, edge.label.color = "white", edge.label.fill = "lightsteelblue4",
           label=TRUE, legend.position = "none", max_size=label_size, layout.exp = 0.1)
  }
}
