# WARNING - Generated by {fusen} from dev/NeighborFinder_flat.Rmd: do not edit by hand

#' metadata
#'
#'#' @format A list of dataframes corresponding to metadata, giving more information on each patient.
#' \describe{
#'   \item{ CRC_JPN }{  dataframe with only Japanese patients diagnosed with colorectal cancer }
#'   \item{ CRC_CHN }{  dataframe with only Chinese patients diagnosed with colorectal cancer }
#'   \item{ CRC_EUR }{  dataframe with only European patients diagnosed with colorectal cancer }
#'   \item{ CRC_JPN_CHN_EUR }{  dataframe with patients diagnosed with colorectal cancer from the 3 previous countries }
#' }
#' @source https://entrepot.recherche.data.gouv.fr/dataset.xhtml?persistentId=doi:10.57745/7IVO3E
"metadata"
