# WARNING - Generated by {fusen} from dev/NeighborFinder_flat.Rmd: do not edit by hand

#' Correspondence between msp name and bacteria name
#' 
#' @param msp String. The name of the msp, can be a single one or a list
#' @param taxo Dataframe. The dataframe gathering the taxonomic correspondence information
#' @param col_msp_id String. The name of the column with the msp names in taxo
#'
#' @return Dictionary. The name of the bacteria, can be a single one or a list
#' @export
#' @examples
#' df_taxo<-data.frame(msp_name=c("msp_1","msp_2","msp_3","msp_4"),
#'                     genus=c("A","B","C","D"),
#'                     species=c("A a","B a","C c","D b"))
#' # Correspondence for one specific msp
#' msp_to_bact("msp_1", taxo=df_taxo, col_msp_id = "msp_name")
#' # or for several msps
#' msp_to_bact(c("msp_1","msp_3","msp_4"), taxo=df_taxo, col_msp_id = "msp_name")
#' # and if one msp is repeated
#' msp_to_bact(c("msp_1","msp_1","msp_2"), taxo=df_taxo, col_msp_id = "msp_name")

msp_to_bact<-function(msp, taxo, col_msp_id="id_mgs"){
  species_dict <- taxo %>% dplyr::select(all_of(col_msp_id), species) %>% tibble::deframe() 
  species_dict[msp] %>% unname() %>% as.character()
}
