# WARNING - Generated by {fusen} from dev/flat_NeighborFinder.Rmd: do not edit by hand # nolint: line_length_linter.

#' Pipe operator
#'
#' See \code{magrittr::\link[magrittr:pipe]{\%>\%}} for details.
#'
#' @name %>%
#' @rdname pipe
#' @keywords internal
#' @export
#' @importFrom magrittr %>%
#' @usage lhs \%>\% rhs
NULL
