# WARNING - Generated by {fusen} from dev/NeighborFinder_flat.Rmd: do not edit by hand

#' Extract edges in graph involving any msp in bact_of_interest set
#' 
#' @param data_with_taxo Dataframe. The abundance table merged with the species names. Required format: species are the rows and samples are the columns. The first column must be the species name, the second is the msps name, and each subsequent column is a sample
#' @param graph_file Dataframe. The object generated by graph_step() function
#' @param col_msp_id String. The name of the column with the msp names in taxo
#' @param bact_of_interest String. The name of the bacteria or species of interest
#'
#' @return Dataframe. The dataframe of edges in the graph involving msps corresponding to bact_of_interest and their corresponding prevalences.
#' @export
#' @examples
#' tiny_data<-data.frame(species=c("One bacteria","One bacterium L","One bacterium G","Two bact"),
#'                       msp_name=c("msp_1","msp_2","msp_3","msp_4"),
#'                       SAMPLE1=c(0,1.328425e-06,0,1.527688e-07),
#'                       SAMPLE2=c(1.251707e-07,1.251707e-07,3.985320e-07,0),
#'                       SAMPLE3=c(0,0,4.926046e-09,5.626392e-06),
#'                       SAMPLE4=c(0,0,2.98320e-05,0))
#' tiny_graph<-graph_step(tiny_data, col_msp_id="msp_name", type="fpkm") %>% suppressWarnings()
#'
#' tiny_truth <-prev_for_selected_nodes(tiny_data, tiny_graph, col_msp_id="msp_name", bact_of_interest="bacterium")

prev_for_selected_nodes <- function(data_with_taxo, graph_file, col_msp_id, bact_of_interest=NULL) {
  if (is.null(graph_file)) {stop("Please generate the graph beforehand with graph_step() function")}
  else {G <- graph_file} 
  
  ## Compute prevalence of all species
  prev_df <- tibble::tibble(id_msp = data_with_taxo %>% dplyr::pull(paste(col_msp_id)),
                    prev = data_with_taxo %>% dplyr::select(-species, -all_of(col_msp_id)) %>% data.matrix() %>% `>`(0) %>% rowMeans())
  
  ## Extract edges starting or ending from bacteria of interest
  if (is.null(bact_of_interest)) {bact_index <- seq_along(G$species)} 
  else {bact_index <- G$species %>% stringr::str_detect(paste(bact_of_interest))}
  
  G_bact <- G[bact_index, ] %>% dplyr::select(-species) 
  
  if (!nrow(G_bact)){return(tibble::tibble())}
  
  truth <- G_bact[, colSums(G_bact) != 0] %>% tibble::as_tibble(rownames = "msp1") %>% 
    tidyr::pivot_longer(-msp1, values_to = "Edge", names_to = "msp2") %>% 
    dplyr::select(order(colnames(.))) %>% 
    dplyr::filter(Edge!=0) %>% dplyr::select(-Edge) 
  ## Add prevalences for msp1 and msp2
  truth <- truth %>% 
    dplyr::left_join(prev_df, by = dplyr::join_by(msp1 == id_msp)) %>% 
    ## and rename prev with suffix matching corresponding msp
    dplyr::left_join(prev_df, by = dplyr::join_by(msp2 == id_msp), suffix = c("1", "2"))
  truth
}
