# WARNING - Generated by {fusen} from dev/NeighborFinder_flat.Rmd: do not edit by hand

#' Extract edges in graph involving any module in object_of_interest set
#' 
#' @param data_with_annotation Dataframe. The abundance table merged with the module names. Required format: modules are the rows and samples are the columns. The first column must be the modules name (e.g. species), the second is the module ID (e.g. msp), and each subsequent column is a sample
#' @param graph_file Dataframe. The object generated by graph_step() function
#' @param col_module_id String. The name of the column with the module names in annotation_table
#' @param annotation_level String. The name of the column with the level to be studied. Examples: species, genus, level_1
#' @param object_of_interest String. The name of the bacteria or species of interest or a key word in the functional module definition
#'
#' @return Dataframe. The dataframe of edges in the graph involving modules corresponding to object_of_interest and their corresponding prevalences.
#' @export
#' @examples
#' tiny_data<-data.frame(species=c("One bacteria","One bacterium L","One bacterium G","Two bact"),
#'                       msp_name=c("msp_1","msp_2","msp_3","msp_4"),
#'                       SAMPLE1=c(0,1.328425e-06,0,1.527688e-07),
#'                       SAMPLE2=c(1.251707e-07,1.251707e-07,3.985320e-07,0),
#'                       SAMPLE3=c(0,0,4.926046e-09,5.626392e-06),
#'                       SAMPLE4=c(0,0,2.98320e-05,0))
#' tiny_graph<-graph_step(tiny_data, col_module_id="msp_name", annotation_level="species", seed=20242025) %>% suppressWarnings()
#'
#' tiny_truth <-prev_for_selected_nodes(tiny_data, tiny_graph, col_module_id="msp_name", annotation_level="species", object_of_interest="bacterium")

prev_for_selected_nodes <- function(data_with_annotation, graph_file, col_module_id, annotation_level, object_of_interest=NULL) {
  if (is.null(graph_file)) {stop("Please generate the graph beforehand with graph_step() function")}
  else {G <- graph_file} 
  
  ## Compute prevalence of all modules at the studied level
  prev_df <- tibble::tibble(id_module = data_with_annotation %>% dplyr::pull(paste(col_module_id)),
                    prev = data_with_annotation %>% dplyr::select(-!!rlang::sym(annotation_level), -all_of(col_module_id)) %>% data.matrix() %>% `>`(0) %>% rowMeans())
  
  ## Extract edges starting or ending from the object of interest
  if (is.null(object_of_interest)) {object_index <- seq_along(G %>% dplyr::pull(!!rlang::sym(annotation_level)))} 
  else {object_index <- G %>% dplyr::pull(!!rlang::sym(annotation_level)) %>% stringr::str_detect(paste(object_of_interest))}
  
  G_object <- G[object_index, ] %>% dplyr::select(-!!rlang::sym(annotation_level)) 
  
  if (!nrow(G_object)){return(tibble::tibble())}
  
  truth <- G_object[, colSums(G_object) != 0] %>% tibble::as_tibble(rownames = "node1") %>% 
    tidyr::pivot_longer(-node1, values_to = "Edge", names_to = "node2") %>% 
    dplyr::select(order(colnames(.))) %>% 
    dplyr::filter(Edge!=0) %>% dplyr::select(-Edge) 
  ## Add prevalences for node1 and node2
  truth <- truth %>% 
    dplyr::left_join(prev_df, by = dplyr::join_by(node1 == id_module)) %>% 
    ## and rename prev with suffix matching corresponding module
    dplyr::left_join(prev_df, by = dplyr::join_by(node2 == id_module), suffix = c("1", "2"))
  truth
}
