# WARNING - Generated by {fusen} from dev/NeighborFinder_flat.Rmd: do not edit by hand

#' Give results from cvglm_to_coeffs_by_bact() for each filtering top percentage
#' 
#' @param res_glm Dataframe. The one resulting from cvglm_to_coeffs_by_bact()
#' @param filtering_list List of numeric. The filtering top percentages to be studied. Required format is: 10 for the top 10% 
#' 
#' @return List of dataframes. Each element of the list corresponds to a dataframe of detected edges by filtering top percentage
#' @export
#' @examples
#' data(data)
#' #Simple example
#' normed_JPN <-norm_data(data$CRC_JPN, col_msp_id="msp_id", prev_list=c(0.20, 0.25, 0.30), type="fpkm")
#' neighbors_JPN<-cvglm_to_coeffs_by_bact(list_dfs=normed_JPN, test_msp=c("msp_0030","msp_0345"), seed=20232024)
#' filtered_neighbors_JPN<-res_by_filtering(neighbors_JPN, filtering_list=c(10,15,20))

res_by_filtering<-function(res_glm, filtering_list){
 
 filtering_glm<-function(filtering_top){
  res_glm %>% dplyr::group_by(prev_level) %>% 
   dplyr::filter(abs(coef) > quantile(abs(coef),1-filtering_top/100)) %>% 
   dplyr::ungroup()
 }
 
 purrr::map(filtering_list, filtering_glm) %>% rlang::set_names(filtering_list)
}
