# WARNING - Generated by {fusen} from dev/flat_NeighborFinder.Rmd: do not edit by hand # nolint: line_length_linter.

#' Simulate a graph with clusters
#'
#' This function simulates a community-based graph with `k` (equal-size) clusters, `p` nodes, a ratio `r` between intra-cluster and inter-cluster connectivity and a target graph density `dens`
#'
#' @return A graph with clusters as an adjacency matrix
#'
#' @noRd
#' @examples
#' SimCluster(p = 4, k = 3, dens = 4, r = 50)
#' SimCluster(p = 4, k = 3, dens = 4, r = 50, mode = "igraph>=2.2")
SimCluster <- function(p, k, dens, r, mode = c("igraph<2.2", "igraph>=2.2")) {
  mode <- match.arg(mode)

  ## Legacy version of the function for retrocompatibility with previous results
  if (mode == "igraph<2.2") {
    ## Ideal case, user-provided values are "admissible"
    beta <- dens / (r / k + (k - 1) / k)
    alpha <- r * beta

    while (alpha > 1) {
      r <- 0.9 * r
      beta <- dens / (r / k + (k - 1) / k)
      alpha <- r * beta
    }
    Z <- t(stats::rmultinom(p, 1, rep(1 / k, k)))
    groupe <- Z %*% 1:k
    Z <- Z %*% t(Z)
    diag(Z) <- 0
    ZZ <- ToVec(Z)
    G <- ToSym(stats::rbinom(p * (p - 1) / 2, 1, alpha * ZZ + beta * (1 - ZZ)))
    G[is.na(G)] <- 0
    return(G)
  }

  ## Modern handling of NA in adjacency matrices
  if (mode == "igraph>=2.2") {
    if (r < 1) {
      stop("To achieve a cluster-like structure, provide a value of r > 1.")
    }

    alpha <- dens / (1 / k + (k - 1) / (k * r))

    if (alpha > 1) {
      r_max <- (k - 1) / (k * dens - 1)
      dens_max <- (1 / k + (k - 1) / (k * r))
      warning(
        paste0(
          "User-specified values are not admissible, consider decreasing k, dens or r.\n  Maximum admissible values for dens is ",
          round(dens_max, 3),
          " and for r is ",
          round(r_max, 3)
        )
      )
    }

    if (r_max < 1) {
      message(paste0(
        "Maximum value for r is below 1, decreasing target density to ",
        round(0.99 * dens_max, 3)
      ))
      dens <- 0.99 * dens_max
    } else {
      cat(paste0(
        "Maximum value for r is below 1, decreasing target intra/inter ratio to ",
        round(0.99 * r_max, 3)
      ))
      r <- 0.99 * r_max
    }

    alpha <- dens / (1 / k + (k - 1) / (k * r))
    beta <- alpha / r

    Z <- t(stats::rmultinom(p, 1, rep(1 / k, k)))
    # groupe <- Z %*% 1:k
    Z <- Z %*% t(Z)
    diag(Z) <- 0
    ZZ <- ToVec(Z)
    G <- ToSym(stats::rbinom(p * (p - 1) / 2, 1, alpha * ZZ + beta * (1 - ZZ)))
    return(G)
  }
}

ToSym <- function(A.vec) {
  n <- (1 + sqrt(1 + 8 * length(A.vec))) / 2
  A.mat <- matrix(0, n, n)
  A.mat[upper.tri(A.mat)] <- A.vec
  A.mat <- A.mat + t(A.mat)
  A.mat
}

ToVec <- function(A.mat) {
  return(suppressMessages(A.mat[upper.tri(A.mat)]))
}
