# WARNING - Generated by {fusen} from dev/flat_NeighborFinder.Rmd: do not edit by hand # nolint: line_length_linter.

#' List the simulated count tables by level of prevalence
#'
#' @param data_with_annotation Dataframe. The abundance table merged with the module names. Required format: modules are the rows and samples are the columns. The first column must be the modules name (e.g. species), the second is the module ID (e.g. msp), and each subsequent column is a sample
#' @param prev_list List of numeric. The prevalences to be studied. Required format is decimal: 0.20 for 20% of prevalence.
#' @param graph_file Dataframe. The object generated by graph_step() function
#' @param col_module_id String. The name of the column with the module names in data_with_annotation
#' @param annotation_level String. The name of the column with the level to be studied. Examples: species, genus, level_1
#' @param sample_size Numeric. The size to be considerated, the value of 500 is recommended
#' @param seed Numeric. The seed number, ensuring reproducibility
#' @param verbatim Boolean. Controls verbosity
#' @param data_type String. Enables the treatment of 16S data with "16S", default value is "shotgun"
#'
#' @return List of dataframes. Each element of the list corresponds to a level of prevalence and is a simulated abundance table
#' @export
#' @examples
#' tiny_data <- data.frame(
#'   species = c("One bacteria", "One bacterium L", "One bacterium G", "Two bact"),
#'   msp_name = c("msp_1", "msp_2", "msp_3", "msp_4"),
#'   SAMPLE1 = c(0, 1.328425e-06, 0, 1.527688e-07),
#'   SAMPLE2 = c(1.251707e-07, 1.251707e-07, 3.985320e-07, 0),
#'   SAMPLE3 = c(0, 0, 4.926046e-09, 5.626392e-06),
#'   SAMPLE4 = c(0, 0, 2.98320e-05, 0)
#' )
#'
#' tiny_graph <- graph_step(tiny_data, col_module_id = "msp_name", annotation_level = "species", seed = 20242025) %>% suppressWarnings()
#'
#' tiny_sims <- simulate_by_prevalence(tiny_data, prev_list = c(0.20, 0.30), graph_file = tiny_graph, col_module_id = "msp_name", annotation_level = "species", sample_size = 500, seed = 20242025)
simulate_by_prevalence <- function(data_with_annotation, prev_list, graph_file = NULL, col_module_id, annotation_level, sample_size = 500, seed, verbatim = FALSE, data_type = "shotgun") {
  set.seed(seed)
  if (is.null(graph_file)) {
    stop("Please generate the graph beforehand with graph_step() function")
  } else {
    G <- graph_file
  }
  if (verbatim) {
    cat("Generating simulated tables for each level of prevalence...\n")
  }

  abund_table <- data_with_annotation %>% dplyr::select(-all_of(col_module_id), -!!rlang::sym(annotation_level))
  modules <- data_with_annotation %>% dplyr::pull(col_module_id)
  sample_id <- abund_table %>% colnames()

  sim_one_prev <- function(prev) {
    if (verbatim) {
      cat(glue::glue("p{100*prev}"), sep = "\n")
    }
    if (data_type == "shotgun") {
      # Generating count table
      df_counts <- get_count_table(abund.table = abund_table, sample.id = sample_id, msp = modules, prev.min = prev, verbatim = FALSE)$data
    } else if (data_type == "16S") {
      prev_df <- tibble::tibble(
        id_module = modules,
        prevalence = abund_table %>% data.matrix() %>% `>`(0) %>% rowMeans()
      )
      prev_df_filtered <- prev_df %>% dplyr::filter(prevalence > 0.15)
      data_with_annotation_filtered <- data_with_annotation %>% dplyr::filter(!!rlang::sym(col_module_id) %in% prev_df_filtered$id_module)
      df_counts <- data_with_annotation_filtered %>%
        dplyr::select(-!!rlang::sym(annotation_level), -!!rlang::sym(col_module_id)) %>%
        t()
      colnames(df_counts) <- data_with_annotation_filtered %>% dplyr::pull(paste(col_module_id))
    }
    # Simulation of count table
    df_sim <- new_synth_data(df_counts, n = sample_size, graph = as.matrix(G %>% dplyr::select(-!!rlang::sym(annotation_level))), verbatim = FALSE, seed = seed)
    # Transformed matrix with mclr
    df_norm <- mclr(df_sim$counts)
    colnames(df_norm) <- colnames(df_counts)
    df_norm %>% as.matrix()
  }

  purrr::map(prev_list, sim_one_prev) %>% rlang::set_names(prev_list)
}
