# WARNING - Generated by {fusen} from dev/NeighborFinder_flat.Rmd: do not edit by hand

#' List the simulated count tables by level of prevalence
#' 
#' @param data_with_taxo Dataframe. The abundance table merged with the species names. Required format: species are the rows and samples are the columns. The first column must be the species name, the second is the msps name, and each subsequent column is a sample
#' @param prev_list List of numeric. The prevalences to be studied. Required format is decimal: 0.20 for 20% of prevalence.
#' @param graph_file Dataframe. The object generated by graph_step() function
#' @param col_msp_id String. The name of the column with the msp names in data_with_taxo
#' @param sample_size Numeric. The size to be considerated, the value of 500 is recommended
#' @param seed Numeric. The seed number, ensuring reproducibility
#'
#' @return List of dataframes. Each element of the list corresponds to a level of prevalence and is a simulated abundance table
#' @export
#' @examples
#' tiny_data<-data.frame(species=c("One bacteria","One bacterium L","One bacterium G","Two bact"),
#'                       msp_name=c("msp_1","msp_2","msp_3","msp_4"),
#'                       SAMPLE1=c(0,1.328425e-06,0,1.527688e-07),
#'                       SAMPLE2=c(1.251707e-07,1.251707e-07,3.985320e-07,0),
#'                       SAMPLE3=c(0,0,4.926046e-09,5.626392e-06),
#'                       SAMPLE4=c(0,0,2.98320e-05,0))
#'
#' tiny_graph<-graph_step(tiny_data, col_msp_id="msp_name", type="fpkm") %>% suppressWarnings()
#'
#' tiny_sims<-simulate_by_prevalence(tiny_data, prev_list=c(0.20,0.30), graph_file=tiny_graph, col_msp_id="msp_name", sample_size=500, seed=20232024)

simulate_by_prevalence <- function(data_with_taxo, prev_list, graph_file=NULL, col_msp_id, sample_size=500, seed) {
  set.seed(seed)
  if (is.null(graph_file)) {stop("Please generate the graph beforehand with graph_step() function")}
  else {G <- graph_file}  
  cat("Generating simulated tables for each level of prevalence...\n")
  
  abund_table <- data_with_taxo %>% dplyr::select(-all_of(col_msp_id), -species)
  mgs <- data_with_taxo %>% dplyr::pull(col_msp_id)
  sample_id <- abund_table %>% colnames()
  
  sim_one_prev <- function(prev) {
    cat(glue::glue("p{100*prev}"), sep = "\n")
    # Generating count table
    df_counts <- OneNet::get_count_table(abund.table=abund_table, sample_id=sample_id, mgs=mgs, prev.min=prev, verbatim=FALSE)
    # Simulation of count table
    df_sim <- OneNet::new_synth_data(df_counts$data, n=sample_size, graph=as.matrix(G %>% dplyr::select(-species)), plot=FALSE, verbose=FALSE, seed=seed)
    #Transformed matrix with mclr
    df_norm <- SPRING::mclr(df_sim$counts)
    colnames(df_norm)<-colnames(df_counts$data)
    df_norm %>% as.matrix()
  }
  
  purrr::map(prev_list, sim_one_prev) %>% rlang::set_names(prev_list)
}
