# WARNING - Generated by {fusen} from dev/NeighborFinder_flat.Rmd: do not edit by hand # nolint: line_length_linter.

#' Simulate data (extracted from OneNet package)
#' Generates synthetic count data based on empirical cumulative distribution (ecdf) of real count data
#'
#' @param real_data Matrix. Contains real count data of size n by p
#' @param Sigma Matrix. Covariance structure of size p by p
#' @param n Numeric. Number of samples
#' @param seed Numeric. Seed number for data generation
#' @param verbatim Boolean. If TRUE: iteration and index calculation for each step are printed out
#' 
#' @return Matrix. The vector from the upper triangular part of A.mat
#' @export

simulate_from_ecdf <- function (real_data, Sigma, n, seed=10010, verbatim=FALSE){
  p <- ncol(real_data)
  if (!is.null(seed)) { set.seed(seed) }
  mv_norm <- mvtnorm::rmvnorm(n, mean=rep(0, p), sigma=stats::cov2cor(Sigma))
  mv_unif <- stats::pnorm(mv_norm)
  ## Matrix of simulated counts
  sim_counts <- matrix(0, n, p)
  ## For each species, apply the inverse of the empirical distribution
  ## function to the uniform r.v.
  for (j in 1:p) {
    ## quantile(x, ., type = 1) is the inverse of the empirical distribution function of x
    sim_counts[, j] <- quantile(x=real_data[, j], probs=mv_unif[, j], names=FALSE, type=1)
  }
  sim_counts
}
