# WARNING - Generated by {fusen} from dev/flat_NeighborFinder.Rmd: do not edit by hand # nolint: line_length_linter.

#' Simulate data
#' Generates synthetic count data based on empirical cumulative distribution (ecdf) of real count data
#'
#' @param real_data Matrix. Contains real count data of size n by p
#' @param Sigma Matrix. Covariance structure of size p by p
#' @param n Numeric. Number of samples
#' @param seed Numeric. Seed number for data generation
#' @param verbatim Boolean. If TRUE: iteration and index calculation for each step are printed out
#'
#' @source This function is adapted from the same name function in OneNet package (version 0.3.1),
#'         which is licensed under the MIT License.
#'         Original copyright (c) 2021-2024 INRAE.
#'
#'         The MIT License text for the original package is as follows:
#'         ---
#'         Permission is hereby granted, free of charge, to any person obtaining a copy
#'         of this software and associated documentation files (the "Software"), to deal
#'         in the Software without restriction, including without limitation the rights
#'         to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#'         copies of the Software, and to permit persons to whom the Software is
#'         furnished to do so, subject to the following conditions:
#'
#'         The above copyright notice and this permission notice shall be included in all
#'         copies or substantial portions of the Software.
#'
#'         THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#'         IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#'         FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#'         AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#'         LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#'         OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#'         SOFTWARE.
#'         ---
#'
#' @return Matrix. The vector from the upper triangular part of A.mat
#' @export

simulate_from_ecdf <- function(
  real_data,
  Sigma,
  n,
  seed = 10010,
  verbatim = FALSE
) {
  p <- ncol(real_data)
  if (!is.null(seed)) {
    set.seed(seed)
  }
  mv_norm <- mvtnorm::rmvnorm(
    n,
    mean = rep(0, p),
    sigma = stats::cov2cor(Sigma)
  )
  mv_unif <- stats::pnorm(mv_norm)
  ## Matrix of simulated counts
  sim_counts <- matrix(0, n, p)
  ## For each species, apply the inverse of the empirical distribution
  ## function to the uniform r.v.
  for (j in 1:p) {
    ## quantile(x, ., type = 1) is the inverse of the empirical distribution function of x
    sim_counts[, j] <- quantile(
      x = real_data[, j],
      probs = mv_unif[, j],
      names = FALSE,
      type = 1
    )
  }
  sim_counts
}
