# WARNING - Generated by {fusen} from dev/flat_NeighborFinder.Rmd: do not edit by hand # nolint: line_length_linter.

#' taxo
#'
#' #' @format A dataframe with 2537 msps (rows) and 4 columns:
#' \describe{
#'   \item{ msp_id }{  string }
#'   \item{ species }{  string }
#'   \item{ genus }{  string }
#'   \item{ catalogue }{  string indicating gut and/or oral }
#' }
#' @source https://entrepot.recherche.data.gouv.fr/dataset.xhtml?persistentId=doi:10.57745/7IVO3E
"taxo"
