# WARNING - Generated by {fusen} from dev/NeighborFinder_flat.Rmd: do not edit by hand

#' Render a table gathering precision and recall rates before and after filtering on coefficient values
#' 
#' @param df_before Dataframe. The one of true neighbors
#' @param df_after Dataframe. The one of detected neighbors
#' @param prevs List of numeric. The prevalences to be studied. Required format is decimal: 0.20 for 20% of prevalence
#' 
#' @return Dataframe. Returns the precision and recall rates before and after the modification
#' @export
#' @examples
#' data(data)
#' data(taxo)
#' data(graphs)
#' #Generate dataframe with true neighbors
#' df_true<-truth_by_prevalence(edge_table = prev_for_selected_nodes(data$CRC_JPN, graphs$CRC_JPN, "msp_id", "Klebsiella", annotation_level="species"), prev_list=c(0.20,0.30))
#' #Generate dataframe with detected neighbors
#' normed_JPN<-norm_data(data$CRC_JPN, col_module_id="msp_id", annotation_level="species", prev_list=c(0.20, 0.25, 0.30))
#' df_detected<-cvglm_to_coeffs_by_object(list_dfs=normed_JPN, test_module=identify_module("Klebsiella",taxo,"msp_id", annotation_level="species"), seed=20232024)
#' #Use final_step() to gather both
#' neighbors<-final_step(df_true, df_detected)
#'
#' neighbors_modif<-final_step(df_true, res_by_filtering(df_detected, filtering_list=c(10,50)))
#'
#' scores<-test_filter(neighbors, neighbors_modif, prevs=names(df_true))

test_filter<-function(df_before, df_after, prevs = NULL){
  scores_before <- df_before %>%  dplyr::mutate(
    precision_before = purrr::pmap_dbl(list(node2_true, node2_detected), compute_precision),
    recall_before = purrr::pmap_dbl(list(node2_true, node2_detected), compute_recall))
  scores_after <- df_after %>%  dplyr::mutate(
    precision_after  = purrr::pmap_dbl(list(node2_true, node2_detected), compute_precision),
    recall_after = purrr::pmap_dbl(list(node2_true, node2_detected), compute_recall))
  
  if(!nrow(scores_before) | !nrow(scores_after)){ return(tibble::tibble()) }
  else{
  score_table <-  dplyr::full_join(scores_before, scores_after, by=c("prev_level","node1")) %>% 
     dplyr::select(prev_level, filtering_top, precision_before, recall_before, precision_after, recall_after) %>% 
     dplyr::mutate_all(~ replace(., is.na(.), 0))
  
  res <- score_table %>%  dplyr::summarize(across(precision_before:recall_after, mean), .by = c(prev_level,filtering_top)) %>% as.data.frame()
  if (is.null(prevs)) {return(res)}
  else {return(res %>%  dplyr::filter(prev_level %in% prevs))}
  }
}
