# WARNING - Generated by {fusen} from dev/NeighborFinder_flat.Rmd: do not edit by hand

#' Display network after applying NeighborFinder
#' 
#' @param res_NeighborFinder Dataframe. The result from apply_NeighborFinder()
#' @param taxo Dataframe. The dataframe gathering the taxonomic correspondence information
#' @param col_msp_id String. The name of the column with the msp names in taxo
#' @param bact_of_interest String. The name of the bacteria or species of interest
#' @param taxo_option Boolean. Default value is False. If True: labels on nodes become species names instead of msps names
#' @param node_size Numeric. The parameter to adjust size of nodes
#' @param label_size Numeric. The parameter to adjust size of labels
#' @param species_color String. The name of the color to differentiate the nodes corresponding to 'bact_of_interest' from the other msps
#' @param seed Numeric. The seed number, ensuring reproducibility
#' 
#' @return Network. Visualization of NeighborFinder results
#' @export
#' @examples
#' data(taxo)
#' data(data)
#' res_CRC_JPN<-apply_NeighborFinder(data$CRC_JPN, bact_of_interest="Escherichia coli", col_msp_id="msp_id", seed=20232024)
#'
#' visualize_network(res_CRC_JPN, taxo, bact_of_interest="Escherichia coli", col_msp_id="msp_id", label_size=5)
#' #With species names instead of msps names
#' visualize_network(res_CRC_JPN, taxo, bact_of_interest="Escherichia coli", col_msp_id="msp_id", label_size=5, taxo_option=TRUE, seed=2)
#' #With esthetic changes
#' visualize_network(res_CRC_JPN, taxo, bact_of_interest="Escherichia coli", col_msp_id="msp_id", taxo_option=TRUE, node_size=15, label_size=6, species_color= "orange", seed=2)

visualize_network<-function(res_NeighborFinder, taxo, col_msp_id, bact_of_interest, taxo_option=FALSE, node_size=12, label_size=4, species_color="cadetblue2", seed=NULL){
  if (!nrow(res_NeighborFinder)) {return(message("No neighbors were found."))}
  if (!taxo_option){
    #Give more visual weight to edges
    res <- res_NeighborFinder %>%  dplyr::mutate(coef=coef*10)
    #Build network
    net <- network::network(res, matrix.type = "edgelist", ignore.eval = FALSE, names.eval = "weights")
    #Identify species of interest in a different color
    palette <- dplyr::if_else(network::network.vertex.names(net) %in% identify_msp(bact_of_interest=bact_of_interest, taxo=taxo, col_msp_id=col_msp_id), species_color, "grey85")
    #Plot network
    if (!is.null(seed)){set.seed(seed)}
    GGally::ggnet2(net, edge.size = "weights", 
           color=palette, edge.color="lightsteelblue4", size=node_size,
           label=TRUE, legend.position = "none", max_size=label_size, layout.exp = 0.1)
  }
  else{
    #Give taxonomic correspondence
    res <- res_NeighborFinder %>%  dplyr::mutate(coef=coef*10) %>% 
       dplyr::mutate(msp1=msp_to_bact(msp=msp1, taxo=taxo, col_msp_id=col_msp_id), 
             msp2=msp_to_bact(msp=msp2, taxo=taxo, col_msp_id=col_msp_id)) 
    #Build network
    net <- network::network(res, matrix.type = "edgelist", ignore.eval = FALSE, names.eval = "weights")
    #Identify species of interest in a different color
    palette <- dplyr::if_else(network::network.vertex.names(net) %in% msp_to_bact(msp=identify_msp(bact_of_interest=bact_of_interest, taxo=taxo, col_msp_id=col_msp_id), 
                                                                  taxo=taxo, col_msp_id=col_msp_id), species_color, "grey85")
    #Plot network
    if (!is.null(seed)){set.seed(seed)}
    GGally::ggnet2(net, edge.size = "weights", 
           color=palette, edge.color="lightsteelblue4", size=node_size,
           label=TRUE, legend.position = "none", max_size=label_size, layout.exp = 0.1)
  }
}
